In [1]:
import os
os.chdir('/Users/thom/Personnel/Scolaire/MIA/snake2-beta-insa-main/data/teamExperiments')
from makeClassifierTrainingSet import *

In [2]:
taskNumber = 2

In [3]:
# Reset all dataframes in case we run parts of the notebook

nonMemberPart = pd.DataFrame()
memberPart = pd.DataFrame()
trainingSet = pd.DataFrame()

In [4]:
privateDataset_Path = "createdSets/Task 1/train/"

memberPart = makeMemberPart(privateDataset_Path, clean = False)
memberPart

              0         1         2         3         4         5         6
0      0.446012  0.518334  0.431132  0.523047  0.536426  0.435405  0.459285
1      0.554049  0.657797  0.597536  0.877250  0.203043  0.617628  0.666556
2      0.109855  0.323959  0.525638  0.392221  0.216225  0.245697  0.570565
3      0.543200  0.454709  0.857446  0.845294  0.644236  0.736287  0.410116
4      0.446997  0.501470  0.507758  0.506773  0.343127  0.563080  0.437678
...         ...       ...       ...       ...       ...       ...       ...
99995  0.222589  0.202058  0.200997  0.111976  0.164268  0.118947  0.136372
99996  0.249106  0.306276  0.346688  0.491848  0.246909  0.000000  0.282744
99997  0.000000  0.035684  0.143039  0.258713  0.120235  0.110461  0.267971
99998  0.469922  0.000000  0.544548  0.658964  0.854855  0.578050  0.468953
99999  0.216710  0.268365  0.293094  0.078505  0.032638  0.176162  0.161707

[100000 rows x 7 columns]

In [5]:
nonMemberPart = makeNonMemberPart(memberPart, taskNumber)
nonMemberPart

KeyboardInterrupt:

In [11]:
trainingSet = createFinalTrainingSet(nonMemberPart, memberPart)
trainingSet

,0,1,2,3,4,5,6,isMember
579792,0.065837,0.361992,0.233044,0.112810,0.048336,0.000000,0.114855,0
573865,0.244788,0.395327,0.681632,0.659479,0.000000,0.309943,0.393721,0
991181,0.475408,0.519122,0.484726,0.861446,0.249636,0.426935,0.462725,0
676182,0.078111,0.134023,0.301306,0.538502,0.646994,0.720195,0.554579,0
112880,0.117356,0.136751,0.244560,0.236075,0.173420,0.038942,0.153343,0
...,...,...,...,...,...,...,...,...
995,0.581778,0.583596,0.745060,0.486469,0.009849,0.901009,0.596703,1
996,0.768456,0.587536,0.498136,0.463361,0.605279,0.617992,0.572307,1
997,0.244485,0.392372,0.470483,0.347445,0.157964,0.427147,0.147736,1
998,0.297109,0.408949,0.574732,0.414192,0.402009,0.330672,0.365280,1
999,0.591218,0.497424,0.530593,0.547276,0.000000,0.397494,0.521683,1